name: dblp-nli
services:
  frontend:
    build:
      context: ./dblp-nli-app
      args:
        API_URL: http://backend:9000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: .
