name: dblp-nli
services:
  frontend:
    build: ./dblp-nli-app
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:9000
    depends_on:
      - backend

  backend:
    build: .
    ports:
      - "127.0.0.1:9000:9000"
